### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by userkim12** [thing-zoo/spring-level2#6]
1. PostResponseDto에는 필드가 많으니 빌더 패턴을 이용해서 생성자를 만드는 것은 어떨까요?
2. PostController와 UserController에서 ResponseEntity를 생성하는 방식이 서로 달라서 통일되는 것도 괜찮을 것 같습니다!
3. GetUsernameFromJwt 메서드는 JwtUtil 클래스 안에 있어도 괜찮지 않을까요?
4. isValidate라는 메서드는 동사가 두 번 들어가니까 isValid 등으로 고치는 것도 좋을 것 같아요
5. PostRequestDto에 validation 애너테이션들이 달려있는데 DTO가 사용되는 곳에서는 @Valid가 없어요..!
6. Dto는 데이터 통신을 위한 오브젝트인데 username이 있으면 보낼 때 token이 아닌 username을 보내줄 수도 있다고 생각합니다.

페어분과 함께 작성한 코드리뷰입니다.
저희도 똑같이 실수한 것들이 있겠지만 일단 보이는 대로 말씀드립니다..🙂

**Comment by dev-krince** [comment]
감사합니다ㅎㅎ 참고하겠습니다~!

**Comment by thing-zoo** [comment]
1. 인자가 Post 객체하나라서 생성자로 생성했는데, 다음에는 빌더를 사용해보겠습니다
2. 아직 responseentity가 익숙하지 않네요 ㅎㅎ 다음에는 통일시켜보겠습니다.
3. 그렇네요 그메소드는 Jwt랑 더 연관깊어서 넣어도 좋을 것 같아요
4. 오타는 전혀 생각못했네요! 얼른 고쳐두겠습니다...ㅎ
5. user부분에만 초점을 맞추느라 post는 안단줄도 몰랐네요! 수정해두겠습니다.
6. 아 네 작성자명이 필요할 거 같아서 넣어뒀는데 그럴수있겠네요!
